{"name": "Проверка получения ошибки изменения данных не авторизованного пользователя", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "self = <allure_commons._allure.fixture object at 0x00000283C0CE7E90>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\nvenv\\Lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.fixture\n    def create_user_for_del():\n        user_data = GenerateUser.creat_user()\n        response = BaseMethods.post_request(URL.MAIN_PAGE_URL + ENDPOINTS.CREATE_USER, user_data)\n        yield user_data, response\n        BaseMethods.del_request(URL.MAIN_PAGE_URL + ENDPOINTS.DELETE_USER_OR_CHANGE_INFO,\n>                                     response.json()['accessToken'])\nE       KeyError: 'accessToken'\n\nconftest.py:14: KeyError"}, "description": "Запросы не авторизованного пользователя на изменения данных, ожидаем ошибку со статусом 401ответ 'You should be authorised'", "steps": [{"name": "Проверка статуса ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [401]>"}, {"name": "code", "value": "401"}], "start": 1704576554991, "stop": 1704576554991}, {"name": "Проверка ответа 'message'", "status": "passed", "parameters": [{"name": "response", "value": "<Response [401]>"}, {"name": "key", "value": "'message'"}, {"name": "text", "value": "'You should be authorised'"}], "start": 1704576554991, "stop": 1704576554991}], "parameters": [{"name": "key_field", "value": "'email'"}, {"name": "new_data", "value": "'curtiswallace@example.net'"}], "start": 1704576554368, "stop": 1704576554994, "uuid": "3a6b151f-1bb0-4769-a663-8836ea278039", "historyId": "d07c90f494dff4527443ab84abbac7d4", "testCaseId": "cc62a3892d640a3300ac7b3f50d56551", "fullName": "tests.test_change_user_data.TestChangeUserData#test_error_change_user_data_not_authorized", "labels": [{"name": "feature", "value": "Проверка изменения пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_change_user_data"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "DESKTOP-RUURDMU"}, {"name": "thread", "value": "6308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_change_user_data"}]}